name: Deploy Frontend to FreeInfinity

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to FreeInfinity
      run: |
        # Copy static files to deploy directory
        cp -r ./* ./deploy/
        
        # Change to the deploy directory
        cd ./deploy/
        
        # Deploy to FreeInfinity using FTP (example)
        # Replace FTP_USERNAME, FTP_PASSWORD, and FTP_SERVER with your actual FTP credentials and server
        curl -T ./* -u $if0_34806115:$NmjOePTLzNR ftp://ftpupload.net/public_html/

