name: Deploy Frontend to FreeInfinity

on:
  push:
    branches:
      - yash_test # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to FreeInfinity
      run: |
        # Deploy frontend files directly from the 'image' directory
        # Deploy to FreeInfinity using FTP (example)
        # Replace FTP_USERNAME, FTP_PASSWORD, and FTP_SERVER with your actual FTP credentials and server
        curl -T ./BMSCE_Companion/image/* -u $if0_34806115:$NmjOePTLzNR ftp://ftpupload.net/public_html/
