name: Deploy Frontend Images to FreeInfinity

on:
  push:
    branches:
      - yash_test # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to FreeInfinity
      run: |
        # List all image files in the 'image' directory and upload each using curl
        for file in ./BMSCE_Companion/image/*; do
          curl -T "$file" -u $if0_34806115:$NmjOePTLzNR ftp://ftpupload.net/public_html/
        done
